### ISSUE TITLE
What is the encryption overhead?

### ISSUE THREAD

**Issue by toonsevrin** [meshbird/meshbird#83]
Are there any benchmarks on how much the bandwidth is reduced by the encryption?

**Comment by pjperez** [comment]
**Disclosure**: I run a SaaS that offers a similar solution (based on SoftEther), but nowhere near as advanced as Meshbird (kudos to the team!!!).

As a networking performance aficionado, I think this is a difficult question to answer and I would recommend you running your own testing. You can easily do it with iPerf; so I've put my money where my mouth is and ran some for you.

Scenario: 2 DigitalOcean Droplets on LON1 datacenter. 2GB RAM each. Ubuntu 14.04 and 16.04.

Iperf3 with 32 parallel TCP connections, **no Meshbird** over their public IP addresses:

(The number next to the sender is the number of retries)

```
[SUM]   0.00-10.00  sec  1.08 GBytes   925 Mbits/sec  5903             sender
[SUM]   0.00-10.00  sec  1.04 GBytes   896 Mbits/sec                  receiver
```

So these droplets are capable of transmitting almost at 1Gbps. That's a nice baseline.

Iperf3 with 32 parallel TCP connections, **with Meshbird** (ran two tests):

```
[SUM]   0.00-12.05  sec  5.08 MBytes  3.54 Mbits/sec  283             sender
[SUM]   0.00-12.05  sec  3.22 MBytes  2.24 Mbits/sec                  receiver

[SUM]   0.00-11.59  sec  7.25 MBytes  5.25 Mbits/sec  400             sender
[SUM]   0.00-11.59  sec  4.63 MBytes  3.35 Mbits/sec                  receiver

```

I tried a third time, but Meshbird crashed on one of the boxes:

```
[remote priv/10.7.82.8] 2017/02/15 18:36:46 Writing to interface...
[remote priv/10.7.82.8] 2017/02/15 18:36:46 EXIT LISTEN
panic: crypto/cipher: input not full blocks

goroutine 239 [running]:
crypto/cipher.(*cbcDecrypter).CryptBlocks(0xc8203f1810, 0xc820602000, 0x144d, 0x144d, 0xc8205e4000, 0x144d, 0x144d)
        /usr/local/go/src/crypto/cipher/cbc.go:92 +0xa6
github.com/gophergala2016/meshbird/secure.DecryptIV(0xc8205e4000, 0x144d, 0x144d, 0xc82009c540, 0x10, 0x18, 0xc82009c540, 0x10, 0x18, 0x0, ...)
        /go/src/github.com/gophergala2016/meshbird/secure/crypt.go:28 +0x1a4
github.com/gophergala2016/meshbird/common.(*RemoteNode).listen(0xc8206f8000, 0xc82010c0a0)
        /go/src/github.com/gophergala2016/meshbird/common/remotenode.go:84 +0x864
created by github.com/gophergala2016/meshbird/common.(*NetTable).AddRemoteNode
        /go/src/github.com/gophergala2016/meshbird/common/net_table.go:81 +0x5eb


(lots of other stuff)
```

(There seem to be crashes on other goroutines too)

On the sender side, I keep seeing thousands of these:

```
[remote priv/10.7.88.35] 2017/02/15 23:40:32 Decode error: timed out waiting for ack
[remote priv/10.7.88.35] 2017/02/15 23:40:32 Decode error: no packet read timeout
```
I can't find reference to the above messages in the code (sorry - I'm not really a coder!)

I thought the problems might be related to the very verbose logging meshbird seems to do in stdout and stderr, so I've sent everything to /dev/null:

`meshbird j > /dev/null 2>&1`

Started the thread again and for ~5 seconds I was getting almost 20Mbps. Still bad, but much better than the previous tests! however it again crashed after 5 secs (or at least lost all connectivity between both peers). Maybe this time was on the sender side:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 9120 root      20   0  362896  20872   8008 S 119.3  1.0   3:51.72 meshbird
```

I am not sure if the above is consequence of some sort of network-level protection in DigitalOcean or due to Meshbird's overhead. I am now trying new iPerf3 tests with one thread and they seem to fully drop shortly after starting. Meshbird crashes on the receiving side, however this might be once again due to packet loss / blackholing from DigitalOcean. This is how it looks:

```
-----------------------------------------------------------
Accepted connection from 10.7.82.8, port 40466
[  5] local 10.7.88.35 port 5201 connected to 10.7.82.8 port 40468
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   167 KBytes  1.37 Mbits/sec
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   2.00-3.00   sec  5.27 KBytes  43.1 Kbits/sec
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   7.00-8.00   sec  59.2 KBytes   486 Kbits/sec
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   9.00-10.00  sec  14.5 KBytes   119 Kbits/sec
[  5]  10.00-10.06  sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-10.06  sec   357 KBytes   290 Kbits/sec   45             sender
[  5]   0.00-10.06  sec   246 KBytes   200 Kbits/sec                  receiver

```

Running a new iPerf3 on the public IP addresses immediately after the above, offers again ~1Gbps.

As per latency the results are pretty good:

ICMP
```
# ping -f 10.7.88.35
PING 10.7.88.35 (10.7.88.35) 56(84) bytes of data.
.^C
--- 10.7.88.35 ping statistics ---
6505 packets transmitted, 6504 received, 0% packet loss, time 8381ms
rtt min/avg/max/mdev = 0.681/3.128/534.407/26.490 ms, pipe 45, ipg/ewma 1.288/1.066 ms
```

TCP
```
# ./gotcping -host 10.7.88.35 -port 5201
Probe 1: Connected to 10.7.88.35:5201, RTT=1.77ms
Probe 2: Connected to 10.7.88.35:5201, RTT=1.76ms
Probe 3: Connected to 10.7.88.35:5201, RTT=2.04ms
Probe 4: Connected to 10.7.88.35:5201, RTT=1.74ms
Probe 5: Connected to 10.7.88.35:5201, RTT=1.79ms
Probe 6: Connected to 10.7.88.35:5201, RTT=1.75ms
Probe 7: Connected to 10.7.88.35:5201, RTT=2.03ms
Probe 8: Connected to 10.7.88.35:5201, RTT=1.89ms
Probe 9: Connected to 10.7.88.35:5201, RTT=2.78ms
Probe 10: Connected to 10.7.88.35:5201, RTT=2.65ms

Probes sent: 10
Successful responses: 10
% of requests failed: 0
Min response time: 1.740765ms
Average response time: 2.020218ms
Median response time: 1.840247ms
Max response time: 2.778665ms

90% of requests were faster than: 2.716493ms
75% of requests were faster than: 2.042955ms
50% of requests were faster than: 1.840247ms
25% of requests were faster than: 1.764399ms
```

Hope this helps! :)

**Comment by pjperez** [comment]
Actually forcing the MSS to e.g. 800 with iPerf3 I can get to finish the test, even with 32 threads!

```
[SUM]   0.00-10.00  sec  8.02 MBytes  6.72 Mbits/sec  542             sender
[SUM]   0.00-10.00  sec  4.17 MBytes  3.50 Mbits/sec                  receiver
```

I think there's some problem with handling packet fragmentation. Linux should be adjusting the MTU if it receives a "fragmentation needed but DF bit set" ICMP as per PMTU...

**Comment by toonsevrin** [comment]
Wow, great analysis 👍 

I haven't really looked into this project but I'd assume it's because every packet is encapsulated with metadata. At the bottom of [this article](http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/) there are similar results on the weaveworks encryption. Anyway, more efficient encryption [is possible](http://packetpushers.net/ipsec-bandwidth-overhead-using-aes/).
I'd assume there are reasons to choose for an encryption with more overhead, though the performance cost is quite severe.
